default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  timeout: 5000
  host: localhost
  username: root

development:
  <<: *default
  database: demo_development

test:
  <<: *default
  database: demo_test

production:
  <<: *default
  database: demo
